### ISSUE TITLE
travis not building

### ISSUE THREAD

**Issue by Ridwanna** [Ridwanna/js-development-environment#1]
![image](https://user-images.githubusercontent.com/29062774/61991880-5ca89300-b04e-11e9-8852-f7a87813439c.png)

i have made the changes but travis is yet to notice it even after clicking 'restart job' on the job's page. what is the way forward ?

**Comment by coryhouse** [comment]
Your code should build. Your travis.yml file is now correct. This screenshot looks like it is from a previous commit where you had a single quote in .yml instead of a double quote. Try triggering a build again.
